version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch-elk
    volumes:
      - 'data01:/usr/share/elasticsearch/data'
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    ports:
      - 9200:9200
    environment:
      - discovery.type: single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
    networks:
      - elastic
  logstash:
    image: logstash:7.10.1
    container_name: logstash
    volumes:
      - './logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
    ports:
      - 5044:5044
      - 9600:9600
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.10.1
    container_name: kibana
    volumes:
      - './kibana/config:/usr/share/kibana/config'
    ports:
      - 5601:5601
      - 9250:9250
    restart: always
    networks:
      - elastic
    depends_on:
      - elasticsearch
volumes:
  data01:
    driver: local

networks:
  elastic:
    ipam:
      driver: default
      config:
      - subnet: "172.21.19.0/24"
